### PR TITLE
Update changelog script

### PR DESCRIPTION
**Pull request by ricardogama**
This PR updates the `changelog` script to use `github_changelog_generator` instead of `github-changes`.

### CODE REVIEW

**Comment by nunorafaelrocha** [comment]
@ricardogama Please update CHANGELOG.md as well.

**Comment by ricardogama** [comment]
@nunorafaelrocha I rather to that on the next release commit.

**Comment by nunorafaelrocha** [comment]
@ricardogama The problem is that in the next release commit other commits from the previous release will show up in the diff.

**Comment by ricardogama** [comment]
@nunorafaelrocha You're right, done.

**Pull request merged**
