### PR TITLE
Better support for SQLite

### PR DESCRIPTION
**Pull request by rummik**
This currently needs a couple changes before it's ready:

- [ ] PostgreSQL supports JSON natively, this PR does not account for that.
- [ ] Unit tests need to be written.
  - I don't currently have a deep enough understanding of Bookshelf to write them currently.  Going to be digging deeper.

This PR is more a request for comments until the above changes are complete.

### CODE REVIEW

**Comment by ricardogama** [comment]
Hey @rummik, thanks for your contribution!

I though of using **SQLite** for testing, since it does not require extra database configuration aside from the knexfile. However the motivation for this plugin was to solve the issues of **knex** while creating queries for **PostgreSQL** on inserts, not selects.

As you well noted, there is an actual need to parse on fetch with **SQLite**. However this isn't a requirement for **PostgreSQL**, like there is no need to stringify on save with **SQLite**.

We need to consider the engine we're using on the `initialize` function and apply the proper events. We should also consider all possible engines on the test suite and provide dedicated tests for each one.

I could add this features I've mentioned and keep this PR open until it is done, although you're free to update your PR with this new changes. WDYT?

**Comment by ricardogama** [comment]
@rummik Just opened #17 with a fix for this, feel free to review it and check for other bugs. Cheers!

**Comment by ricardogama** [comment]
@rummik The #17 fix was released on [1.1.0](https://github.com/seegno/bookshelf-json-columns/releases/tag/1.1.0).

**Comment by rummik** [comment]
Oh, thanks.  Sorry, I completely forgot about it (been very much wrapped up in work, was planning on revisiting as soon as the release was ready ^^;)

**Pull request closed without merging**
